# # SQL LITE SETTINGS
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/dev_m.sqlite3

# test:
#   <<: *default
#   database: db/test_m.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# MYQL SETTINGS

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: avosa
  password: rets
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: befriend_dev

test:
  <<: *default
  database: befriend_test

production:
  <<: *default
  database: befriend_prod
  username: befriend
  password: <%= ENV["befriend_DATABASE_PASSWORD"] %>
